/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ElementsRouteImport } from './routes/elements'
import { Route as DevRouteImport } from './routes/dev'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkSlugRouteImport } from './routes/work.$slug'
import { Route as DevResponsiveRouteImport } from './routes/dev.responsive'
import { Route as ArchiveDateRouteImport } from './routes/archive.$date'

const ElementsRoute = ElementsRouteImport.update({
  id: '/elements',
  path: '/elements',
  getParentRoute: () => rootRouteImport,
} as any)
const DevRoute = DevRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkSlugRoute = WorkSlugRouteImport.update({
  id: '/work/$slug',
  path: '/work/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DevResponsiveRoute = DevResponsiveRouteImport.update({
  id: '/responsive',
  path: '/responsive',
  getParentRoute: () => DevRoute,
} as any)
const ArchiveDateRoute = ArchiveDateRouteImport.update({
  id: '/$date',
  path: '/$date',
  getParentRoute: () => ArchiveRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/archive': typeof ArchiveRouteWithChildren
  '/dev': typeof DevRouteWithChildren
  '/elements': typeof ElementsRoute
  '/archive/$date': typeof ArchiveDateRoute
  '/dev/responsive': typeof DevResponsiveRoute
  '/work/$slug': typeof WorkSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/archive': typeof ArchiveRouteWithChildren
  '/dev': typeof DevRouteWithChildren
  '/elements': typeof ElementsRoute
  '/archive/$date': typeof ArchiveDateRoute
  '/dev/responsive': typeof DevResponsiveRoute
  '/work/$slug': typeof WorkSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/archive': typeof ArchiveRouteWithChildren
  '/dev': typeof DevRouteWithChildren
  '/elements': typeof ElementsRoute
  '/archive/$date': typeof ArchiveDateRoute
  '/dev/responsive': typeof DevResponsiveRoute
  '/work/$slug': typeof WorkSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/archive'
    | '/dev'
    | '/elements'
    | '/archive/$date'
    | '/dev/responsive'
    | '/work/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/archive'
    | '/dev'
    | '/elements'
    | '/archive/$date'
    | '/dev/responsive'
    | '/work/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/archive'
    | '/dev'
    | '/elements'
    | '/archive/$date'
    | '/dev/responsive'
    | '/work/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ArchiveRoute: typeof ArchiveRouteWithChildren
  DevRoute: typeof DevRouteWithChildren
  ElementsRoute: typeof ElementsRoute
  WorkSlugRoute: typeof WorkSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/elements': {
      id: '/elements'
      path: '/elements'
      fullPath: '/elements'
      preLoaderRoute: typeof ElementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev': {
      id: '/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof DevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/$slug': {
      id: '/work/$slug'
      path: '/work/$slug'
      fullPath: '/work/$slug'
      preLoaderRoute: typeof WorkSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/responsive': {
      id: '/dev/responsive'
      path: '/responsive'
      fullPath: '/dev/responsive'
      preLoaderRoute: typeof DevResponsiveRouteImport
      parentRoute: typeof DevRoute
    }
    '/archive/$date': {
      id: '/archive/$date'
      path: '/$date'
      fullPath: '/archive/$date'
      preLoaderRoute: typeof ArchiveDateRouteImport
      parentRoute: typeof ArchiveRoute
    }
  }
}

interface ArchiveRouteChildren {
  ArchiveDateRoute: typeof ArchiveDateRoute
}

const ArchiveRouteChildren: ArchiveRouteChildren = {
  ArchiveDateRoute: ArchiveDateRoute,
}

const ArchiveRouteWithChildren =
  ArchiveRoute._addFileChildren(ArchiveRouteChildren)

interface DevRouteChildren {
  DevResponsiveRoute: typeof DevResponsiveRoute
}

const DevRouteChildren: DevRouteChildren = {
  DevResponsiveRoute: DevResponsiveRoute,
}

const DevRouteWithChildren = DevRoute._addFileChildren(DevRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ArchiveRoute: ArchiveRouteWithChildren,
  DevRoute: DevRouteWithChildren,
  ElementsRoute: ElementsRoute,
  WorkSlugRoute: WorkSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
